config/routes.rb
Rails.application.routes.draw do
  root to: "patients#upload"

  resources :patients, only: [:create, :show, :index, :edit, :update, :delete]
  get "/verified", to: "patients#verified", as: :verified
  get "/confirmation", to: "patients#confirmation", as: :confirmation
  post "/cloudinary", to: "patients#cloudinary", as: :cloudinary
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
require "uri"
require "json"
require "net/http"

class PatientsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_patient, only: %i[create edit show update destroy]

  def upload
  end

  def verified
  end

  def index
    @patients_matched = Patient.all.select { :name.present? }
  end

  # def create
  #   @patient = Patient.new(patient_params)
  #   if @patient.save
  #     render json: @patient.as_json, status: :created
  #   else
  #     render json: @patient.errors, status: :unprocessable_entity
  #   end
  # end

  def show
  end

  def edit
  end

  def update
  @patient.update(patient_params)
  redirect_to patients_path
  # @patient.name = params[:id]
  # @patient.phone_numbers = params[:phone_numbers]
  # @patient.location = params[:location]
  # @patient.details = params[:details]
  # redirect_to patient_path(@patient)
  end

  def destroy
    @patient.destroy
    redirect_to patients_path, status: :see_other
  end

  def cloudinary
    name = params[:results][:name]
    session[:name] = name
    phone_number = params[:results][:phoneNumber]
    session[:phone_number] = phone_number
    url = params[:results][:url]
    session[:url] = url
  end

  def confirmation
    user_photo = session[:url]
    user_name = session[:name]
    user_phone_number = session[:phone_number]
    @patients = Patient.all
    @patient_array = []
    @match = nil

    for patient in @patients
      @patient_array << [["https://res.cloudinary.com/detwvcqim/image/upload/development/#{patient.photo.key}.jpg"], patient.location, patient.phone_numbers]
    end

    # url = URI("https://zylalabs.com/api/30/face+comparison+validator+api/94/compare+image+with+image+url")

    # https = Net::HTTP.new(url.host, url.port)
    # https.use_ssl = true

    # request = Net::HTTP::Post.new(url)
    # request["Authorization"] = ENV['ZYLA']
    # request["Content-Type"] = "application/json"

    @patient_array.each do | patient |
    #   request.body = JSON.dump({

    #     "linkFile1": user_photo.to_s,
    #     "linkFile2": patient[0].join.to_s

    #   })

    #   response = https.request(request)
    #   @data = JSON.parse(response.read_body)

    #   if @data["data"]["similarPercent"] > 0.75
    #     @match = patient[1]
    #   end
    # end

    # response = https.request(request)
    # @data = JSON.parse(response.read_body)

      if 1 > 0.75
        pat = Patient.find_by(location: patient[1])
        @match = patient
        pat.name.push(session[:name])
        pat.details = (session[:phone_number])
        pat.save!
      end
    end

  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name, :phone_numbers, :location, :details, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Find</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital@0;1&display=swap"
      rel="stylesheet"
    />
     <script src="https://example.com/fontawesome/v5.15.4/js/all.js" data-auto-a11y="true" ></script>
  </head>

  <body>
     <%= render 'shared/header' %>
     <%= yield %>
     <%= render 'shared/footer' %>
  </body>
</html>

app/views/patients/_nil.html.erb
<div class = "container-confirmation-nil p-10 justify-center h-screen w-screen">
  <div class = "grid justify-items-center text-center font-poppins">
    <%= image_tag "nil.png", class: "mb-8" %>
    <h1 class = "text-blue-600 text-[35px] leading-9 m-3">Unfortunately there is no match at this moment</h1>
    <hr class="my-3 h-px bg-gray-200 border-0">
    <h3 class = "text-blue-600 text-[15px] leading-6 m-3">Our database is updated <br>daily, please check again <br> in the future</h3>
    <h4 class = "bg-blue-600 text-white px-7 py-3 rounded-lg mt-8 mb-4">Submit another image</h4>
    <h4 class = "text-blue-600 text-[13px] underline">Find other resources</h4>
  </div>
</div>

app/views/patients/_present.html.erb
<div class = "container-confirmation-present p-10 justify-center h-screen w-screen">
  <div class = "grid justify-items-center text-center font-poppins">
    <%= image_tag "match.png", class: "mb-3" %>
    <h5 class = "text-blue-600  text-[13px] px-5 py-2 rounded-lg mt-8 mb-4 stroke-1 stroke-blue-600 bg-blue-100 tracking-widest">REFERENCE ID 918273</h4>
    <h1 class = "text-blue-600 text-[30px] leading-9 mt-6 mb-6 font-bold">Your image matched a potential patient <br> in <%= @match[1] %></h1>
    <hr class="bg-gray-200 border-1">
    <h3 class = "text-blue-600 text-[15px] leading-6 m-3">Please contact <%= @match[2] %> with <br>your reference ID for further details</h3>
    <h4 class = "bg-blue-600 text-white px-7 py-3 rounded-lg mt-8 mb-4">Submit another image</h4>
    <h4 class = "text-blue-600 text-[13px] underline">Find other resources</h4>
  </div>
</div>

app/views/patients/_widget.html.erb
<div class="bg-blue-100 m-4 text-blue-600 flex justify-center flex-col p-5 rounded-lg">
  <div>
    <iframe name="dummyframe" id="dummyframe" style="display: none;"></iframe>
    <form action="" target="dummyframe">
      <label for="name"><p class = "tracking-widest text-center mb-1">Your name</p></label>
      <input type="text" id="name" name="name"><br><br>
      <label for="phoneNumber"><p class = "tracking-widest text-center mb-1">Phone number</p></label>
      <input type="number" id="phoneNumber" name="phoneNumber"><br><br>
    </form>
  </div>
  <div class="flex justify-center w-full">
    <button id="upload_widget" class="cloudinary-button absolute bg-blue-600">Upload an image</button>
    <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></script>
    <script type="text/javascript">
    const csrfToken = document.querySelector("[name='csrf-token']").content;
      var myWidget = cloudinary.createUploadWidget({
        cloudName: 'borhan-cloud',
        uploadPreset: 'z6x5lslv'},
        (error, result) => {
          if (!error && result && result.event === "success") {
            window.location.href = "/confirmation";

          const params = {
            results: {
              url: result.info.url,
              name: document.getElementById("name").value,
              phoneNumber: document.getElementById("phoneNumber").value,
            }
          }

          fetch(`/cloudinary`,
            {
              method: 'POST',
              headers: { "Accept": "application/json", "X-CSRF-Token": csrfToken, "Content-Type": "application/json"},
              body: JSON.stringify(params)
            })
          }
        })

      document.getElementById("upload_widget").addEventListener("click", function(){
          myWidget.open();
        }, false);
    </script>
  </div>
</div>

app/views/patients/confirmation.html.erb
<div data-controller="facial-recognition">

  <% if @match.nil? %>
     <%= render "nil" %>
  <% end %>

  <% if @match.present? %>
    <%= render "present" %>
  <% end %>

</div>

app/views/patients/edit.html.erb
<%# let's create a nice card where to wrap the patient info and edit them %>


<div class="container m-3">
  <div class = "top-container relative h-screen w-screen justify-items-left text-left">
  <%= image_tag "person.png", class: "mb-8" %>
    <div class="card 0 mb-2.5 rounded-md text-blue-600">
      <%= form_with model: @patient do |f| %>
        <%= f.label :name %><br>
        <%= f.text_field :name %><br><br>
        <%= f.label :location %><br>
        <%= f.text_field :location %><br><br>
        <%= f.label :details %><br>
        <%= f.number_field :details %><br>
        <%= f.submit class: "bg-blue-400 rounded p-1 my-4"%>
      <% end %>
    </div>
  </div>
</div>

app/views/patients/index.html.erb
<div class = "top-container h-screen m-5">
  <h2 class ="text-blue-600 text-[30px] leading-8 text-left font-poppins">Dr. Shevchenko</h2>
  <h3 class ="text-blue-600 text-[15px] leading-8 text-left font-poppins mb-3">Central Hospital SBU</h3>

        <% patient = @patients_matched.first %>
          <% link_to edit_patient_path(patient) %>
            <div class="bg-blue-100 rounded-md flex-col p-3 mb-3">
              <div class="patient-info-left">
                <div class="patient-info text-left font-poppins text-blue-600">
                  <p>Patient: <%= patient.name.first %></p>
                </div>
                <br>
                <div class="patient-info text-left font-poppins text-blue-600">
                  <p>Location: <%= patient.location %></p>
                </div>
                <br>
                <div class="patient-info text-left font-poppins text-blue-600">
                  <p>Phone number: 1234567</p>
                </div>
                <br>
                <div class="patient-info text-left font-poppins text-blue-600">
                  <p>Details: <%= patient.details %></p>
                </div>
              </div>
              <div class="patient-info text-left font-poppins">
                <p class = "text-yellow-600 bg-yellow-100 p-2 rounded-lg">
                <%= link_to "Pending", edit_patient_path(patient) %></p>
            </div>


            <br>

  </div>

app/views/patients/upload.html.erb
<div class="container">
  <div class = "top-container relative pt-20 pb-20 grid justify-items-center">
    <h1 class="absolute top-3 text-blue-600 text-[40px] leading-10 text-center z-10 font-poppins">Find <br>a missing <br>person</h1>
    <%= image_tag "home-bg.png", class: "z-0 relative bottom-0" %>
    <div class= "button-container flex justify-center bottom-20 pt-8">
        <%= render "widget"%>
    </div>
  </div>

  <div class= "flex justify-center pl-4 pr-4 text-blue-600 underline">
      See photo guidelines
  </div>

  <div class="login-container flex flex-col justify-center bg-blue-600 p-10 mb-10  mt-10">
    <h2 class = "text-white text-[28px] leading-8 text-center z-10 font-poppins">Are you a <br>healthcare <br>professional?</h2>
    <%= link_to "Admin Portal", patients_path, class: "text-center bg-yellow-500 text-[15px] text-white py-2 px-4 rounded z-10 ml-20 mr-20 mt-5"%>
  </div>

  <div class="about-container flex flex-col m-10">
    <div class="about-descriptions mb-5 mt-5">
      <h2 class ="text-blue-600 text-[30px] leading-8 text-left z-10 mb-4 font-poppins">What is Find?</h2>
      <p class = "leading-6">We help you locate missing loved ones using Facial Recognition software. Upload a photo to begin.</p>
    </div>
    <hr class="my-3 h-px bg-gray-200 border-0 dark:bg-gray-700">
    <div class="about-descriptions mb-5 mt-5">
      <h2 class ="text-blue-600 text-[30px] leading-8 text-left z-10 mb-4 font-poppins">How Does it Work?</h2>
      <p class = "leading-6">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
    </div>
    <hr class="my-3 h-px bg-gray-200 border-0 dark:bg-gray-700">
    <div class="about-descriptions mb-5 mt-5">
      <h2 class ="text-blue-600 text-[30px] leading-8 text-left z-10 mb-4 font-poppins">Photo Guideliness</h2>
      <p class = "leading-6">If possible, your photo should clear and in focus, contain no other objects or people
      and be taken against a plain light-coloured background.</p>
    </div>
  </div>

  <div class="resources-container flex flex-col bg-blue-100">
    <div class="m-10">
      <h2 class ="text-blue-600 text-[30px] leading-8 text-left z-10 mb-4 font-poppins">Other <br>resources<h2>
      <h3 class="bg-blue-600 text-[15px] text-white p-5 mb-3 rounded-md">Ukraine Red Cross</h3>
      <h3 class="bg-blue-600 text-[15px] text-white p-5 mb-3 rounded-md">Official Government of Ukraine</h3>
      <h3 class="bg-blue-600 text-[15px] text-white p-5 mb-3 rounded-md">Refugee Resources</h3>
      <p class="mt-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
    </div>
  </div>

</div>

app/views/shared/_footer.html.erb
<div class = "bg-blue-600 m-0">
<div class = "m-10 pt-7 pb-7 text-white">
  <p>Privacy Policy</p>
  <p>Terms & Conditions</p>
  <i class="fa-light fa-globe"></i><p>EN</p>
</div>
</div>

app/views/shared/_header.html.erb
<div class="flex justify-between p-4">
      <%= image_tag "logo.png", class: "h-8 pt-3" %>
      <%= link_to "Admin", patients_path, class: "bg-yellow-400 px-5 py-2 rounded-md text-white" %>
</div>